name: Deploy React Vite app to Heroku with linting and testing

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint the code
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v3

      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v3

      - run: npm run build

      - uses: aws-actions/aws-cli@v3
        with:
          aws-access-key-id: AKIA2RZP6WZXAD2ZELTZ
          aws-secret-access-key: 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
          region: us-east-1
          command: s3 sync build s3://mybucketrewr343fd
